### ISSUE TITLE
Setup Option for TF Remote State

### ISSUE THREAD

**Issue by knee-berts** [GoogleCloudPlatform/gke-poc-toolkit#28]
Need to setup up a deployment option that allows the user to create and set remote state to a Cloud Storage Bucket. This is also needed to fix cloud build PR triggers so that we can run e2e testing without colocating cluster build and hardening build in the same step.

**Comment by rick-c-goog** [comment]
fork created, everything runs fine so far except one issue at the end to retrieve credentials from the remote state( local state is fine):
 GET_CREDS="$(terraform output  get_credentials)"
get_credentials_command = gcloud container clusters get-credentials --project rick-chen-demo1 --zone us-central1 --internal-ip private-endpoint-cluster
The output variable requested could not be found in the state
file. If you recently added this to your configuration, be
sure to run `terraform apply`, since the state won't be updated
with new output variables until that command is run.

**Comment by knee-berts** [comment]
https://github.com/GoogleCloudPlatform/gke-poc-toolkit/pull/42
